### ISSUE TITLE
I can download videos with myt search but i can't download videos with myt url

### ISSUE THREAD

**Issue by edenlith** [TruncatedDinosour/myt#1]
I followed all of the steps to install myt and got it to work but when I run myt with a Youtube url to download a video I get the output "no video found". If I run myt search "keywords" I get a small list of videos to download and it downloads successfully. 

Is there anything I missed in the tutorial?

**Comment by TruncatedDinosour** [comment]
yeah it doesnt support urls but i dont work on this anymore, im sorry <3

**Comment by edenlith** [comment]
Ah ok sad to know. Thanks for the reply anyway.

**Comment by TruncatedDinosour** [comment]
> Ah ok sad to know. Thanks for the reply anyway.

<3
